import { Reservation } from "@/reservation/domain/entities";

export const data: Reservation[] = [
  {
    id: 1,
    name: "Sid Leither",
    age: 52,
    domicile: "Indonesia",
    complaint: "Future-proofed user-facing info-mediaries",
    therapyExperience: "Accupunture",
    email: undefined,
    gender: "Male",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Total 4th generation frame",
    reservationDatetime: "2025-05-14T11:04:49Z",
    optionalDatetime: undefined,
    phoneNumber: "333-829-4593",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["LEARNING_TRAINING"],
  },
  {
    id: 2,
    name: "Percival Sharp",
    age: 16,
    domicile: "Indonesia",
    complaint: "Grass-roots empowering alliance",
    therapyExperience: "Bekam",
    email: undefined,
    gender: "Male",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Secured client-server support",
    reservationDatetime: "2025-05-20T22:51:07Z",
    optionalDatetime: undefined,
    phoneNumber: "561-417-4204",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "LEARNING_TRAINING",
      "CHIROPRACTIC",
      "HERBAL_SHOPPING",
    ],
  },
  {
    id: 3,
    name: "Clemmy Cornborough",
    age: 61,
    domicile: "Indonesia",
    complaint: "Re-contextualized 6th generation model",
    therapyExperience: "Accupressure",
    email: "pmccaffrey2@comsenz.com",
    gender: "Female",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Fully-configurable executive projection",
    reservationDatetime: "2025-05-19T23:42:38Z",
    optionalDatetime: undefined,
    phoneNumber: "139-243-6179",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["THROAT_GURAH"],
  },
  {
    id: 4,
    name: "Meagan Banbridge",
    age: 41,
    domicile: "Indonesia",
    complaint: "Object-based responsive function",
    therapyExperience: "Sudah pernah",
    email: "zzuppa3@icio.us",
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Balanced empowering alliance",
    reservationDatetime: "2025-05-12T07:06:58Z",
    optionalDatetime: undefined,
    phoneNumber: "773-417-0376",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["HEALTH_CONSULTATION"],
  },
  {
    id: 5,
    name: "Elli Coslitt",
    age: 28,
    domicile: "Indonesia",
    complaint: "Ergonomic bandwidth-monitored attitude",
    therapyExperience: "Accupressure",
    email: "tbullus4@imgur.com",
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Inverse foreground emulation",
    reservationDatetime: "2025-05-17T15:51:10Z",
    optionalDatetime: undefined,
    phoneNumber: "850-614-6918",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["NASAL_GURAH_THERAPY"],
  },
  {
    id: 6,
    name: "Dulci Draye",
    age: 68,
    domicile: "Indonesia",
    complaint: "Progressive systemic support",
    therapyExperience: "Bekam",
    email: "lloosely5@house.gov",
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Balanced hybrid function",
    reservationDatetime: "2025-05-15T19:45:27Z",
    optionalDatetime: undefined,
    phoneNumber: "715-423-0349",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["EYE_GURAH_THERAPY", "FASDHU_THERAPY", "ACUPRESSURE"],
  },
  {
    id: 7,
    name: "Aristotle Blemings",
    age: 55,
    domicile: "Indonesia",
    complaint: "Realigned high-level firmware",
    therapyExperience: "Bekam",
    email: undefined,
    gender: "Male",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Diverse directional intranet",
    reservationDatetime: "2025-05-18T03:49:05Z",
    optionalDatetime: undefined,
    phoneNumber: "701-252-7863",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["ACUPUNCTURE"],
  },
  {
    id: 8,
    name: "Gwenora Andreutti",
    age: 8,
    domicile: "Indonesia",
    complaint: "Exclusive attitude-oriented superstructure",
    therapyExperience: "Accupressure",
    email: "rhouse7@icio.us",
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Realigned optimal encoding",
    reservationDatetime: "2025-05-20T19:46:51Z",
    optionalDatetime: undefined,
    phoneNumber: "521-672-0193",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["ACUPUNCTURE", "THROAT_GURAH", "HERBAL_SHOPPING"],
  },
  {
    id: 9,
    name: "Tate Jolliffe",
    age: 18,
    domicile: "Indonesia",
    complaint: "Automated global capacity",
    therapyExperience: "Accupunture",
    email: "rsalla8@artisteer.com",
    gender: "Male",
    registrationCategory: "RE_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: "Open-source demand-driven framework",
    referredBy: "Fully-configurable asymmetric matrix",
    reservationDatetime: "2025-05-07T02:00:22Z",
    optionalDatetime: undefined,
    phoneNumber: "479-800-8083",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["ACUPRESSURE", "LEARNING_TRAINING"],
  },
  {
    id: 10,
    name: "Ewell Chipperfield",
    age: 16,
    domicile: "Indonesia",
    complaint: "De-engineered uniform framework",
    therapyExperience: "Accupressure",
    email: "ltomei9@fotki.com",
    gender: "Male",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Advanced tangible infrastructure",
    reservationDatetime: "2025-05-11T12:22:08Z",
    optionalDatetime: undefined,
    phoneNumber: "228-362-0818",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "EYE_GURAH_THERAPY",
      "THROAT_GURAH",
      "HEALTH_CONSULTATION",
      "HIJAMAH_BEKAM_THERAPY",
    ],
  },
  {
    id: 11,
    name: "Abie Birdwistle",
    age: 30,
    domicile: "Indonesia",
    complaint: "Cross-group foreground intranet",
    therapyExperience: "Accupunture",
    email: "mtapea@clickbank.net",
    gender: "Male",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Cross-platform executive interface",
    reservationDatetime: "2025-05-16T14:39:39Z",
    optionalDatetime: "2025-05-15T16:25:15Z",
    phoneNumber: "628-501-9964",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["HIJAMAH_BEKAM_THERAPY", "THROAT_GURAH"],
  },
  {
    id: 12,
    name: "Evvy Bandy",
    age: 20,
    domicile: "Indonesia",
    complaint: "Down-sized cohesive task-force",
    therapyExperience: "Bekam",
    email: undefined,
    gender: "Female",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Reduced global paradigm",
    reservationDatetime: "2025-05-15T08:53:34Z",
    optionalDatetime: undefined,
    phoneNumber: "861-472-6874",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "ACUPRESSURE",
      "HIJAMAH_BEKAM_THERAPY",
      "ACUPUNCTURE",
    ],
  },
  {
    id: 13,
    name: "Bonny Totterdell",
    age: 7,
    domicile: "Indonesia",
    complaint: "Fundamental transitional system engine",
    therapyExperience: "Sudah pernah",
    email: "dpolycotec@joomla.org",
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Persevering bi-directional circuit",
    reservationDatetime: "2025-05-09T14:05:13Z",
    optionalDatetime: undefined,
    phoneNumber: "877-248-5856",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "HERBAL_SHOPPING",
      "EYE_GURAH_THERAPY",
      "LEARNING_TRAINING",
      "CHIROPRACTIC",
    ],
  },
  {
    id: 14,
    name: "Nicolais Dowda",
    age: 54,
    domicile: "Indonesia",
    complaint: "Multi-tiered 24/7 orchestration",
    therapyExperience: "Accupunture",
    email: "lbehned@infoseek.co.jp",
    gender: "Male",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Grass-roots composite process improvement",
    reservationDatetime: "2025-05-15T15:13:56Z",
    optionalDatetime: undefined,
    phoneNumber: "579-914-3291",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["HERBAL_SHOPPING", "EYE_GURAH_THERAPY"],
  },
  {
    id: 15,
    name: "Basil Geany",
    age: 34,
    domicile: "Indonesia",
    complaint: "Upgradable human-resource task-force",
    therapyExperience: "Sudah pernah",
    email: "hharrope@privacy.gov.au",
    gender: "Genderqueer",
    registrationCategory: "RE_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "User-centric mission-critical core",
    reservationDatetime: "2025-05-08T01:10:45Z",
    optionalDatetime: undefined,
    phoneNumber: "441-751-7504",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["ACUPUNCTURE"],
  },
  {
    id: 16,
    name: "Micaela Bastian",
    age: 42,
    domicile: "Indonesia",
    complaint: "Triple-buffered well-modulated encryption",
    therapyExperience: "Accupunture",
    email: undefined,
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Programmable context-sensitive flexibility",
    reservationDatetime: "2025-05-07T02:39:37Z",
    optionalDatetime: undefined,
    phoneNumber: "926-655-2174",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "EYE_GURAH_THERAPY",
      "NASAL_GURAH_THERAPY",
      "ACUPUNCTURE",
    ],
  },
  {
    id: 17,
    name: "Tades Sambells",
    age: 25,
    domicile: "Indonesia",
    complaint: "Stomachache",
    therapyExperience: "Sudah pernah",
    email: "mkinnardg@youtube.com",
    gender: "Male",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Progressive full-range adapter",
    reservationDatetime: "2025-05-19T15:00:04Z",
    optionalDatetime: undefined,
    phoneNumber: "862-275-1078",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "HEALTH_CONSULTATION",
      "CHIROPRACTIC",
      "HERBAL_SHOPPING",
      "ACUPUNCTURE",
    ],
  },
  {
    id: 18,
    name: "Lincoln Lennie",
    age: 49,
    domicile: "Indonesia",
    complaint: "Progressive tertiary time-frame",
    therapyExperience: "Accupressure",
    email: "astockneyh@tripod.com",
    gender: "Male",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Enterprise-wide coherent framework",
    reservationDatetime: "2025-05-16T12:48:37Z",
    optionalDatetime: undefined,
    phoneNumber: "453-270-6251",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "LEARNING_TRAINING",
      "HERBAL_SHOPPING",
      "THROAT_GURAH",
    ],
  },
  {
    id: 19,
    name: "Prisca Bogace",
    age: 11,
    domicile: "Indonesia",
    complaint: "Mandatory bandwidth-monitored workforce",
    therapyExperience: "Accupunture",
    email: "jsigfridi@microsoft.com",
    gender: "Female",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: "Jaime Sigfrid",
    accompanyingParticipantComplaint: undefined,
    referredBy: "Operative executive solution",
    reservationDatetime: "2025-05-20T02:23:37Z",
    optionalDatetime: undefined,
    phoneNumber: "470-671-6113",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["CHIROPRACTIC", "NASAL_GURAH_THERAPY"],
  },
  {
    id: 20,
    name: "Gusella Marple",
    age: 14,
    domicile: "Indonesia",
    complaint: "Integrated eco-centric software",
    therapyExperience: "Sudah pernah",
    email: "kganterj@eventbrite.com",
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Innovative high-level adapter",
    reservationDatetime: "2025-05-12T14:54:11Z",
    optionalDatetime: undefined,
    phoneNumber: "333-624-6721",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["FASDHU_THERAPY", "LEARNING_TRAINING"],
  },
  {
    id: 21,
    name: "Constancy Ritchie",
    age: 34,
    domicile: "Indonesia",
    complaint: "Customizable explicit matrix",
    therapyExperience: "Accupunture",
    email: undefined,
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Cloned needs-based workforce",
    reservationDatetime: "2025-05-12T18:34:02Z",
    optionalDatetime: undefined,
    phoneNumber: "939-389-5219",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "EYE_GURAH_THERAPY",
      "FASDHU_THERAPY",
      "HEALTH_CONSULTATION",
      "LEARNING_TRAINING",
    ],
  },
  {
    id: 22,
    name: "Callie Hinder",
    age: 59,
    domicile: "Indonesia",
    complaint: "Sharable systemic algorithm",
    therapyExperience: "Sudah pernah",
    email: "hbohikel@constantcontact.com",
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Mandatory systematic database",
    reservationDatetime: "2025-05-19T23:26:28Z",
    optionalDatetime: undefined,
    phoneNumber: "963-525-4912",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "FASDHU_THERAPY",
      "ACUPUNCTURE",
      "THROAT_GURAH",
      "HEALTH_CONSULTATION",
    ],
  },
  {
    id: 23,
    name: "Wendi Cornelius",
    age: 31,
    domicile: "Indonesia",
    complaint: "Cross-group grid-enabled productivity",
    therapyExperience: "Bekam",
    email: "cvandevliesm@wiley.com",
    gender: "Female",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "User-friendly eco-centric architecture",
    reservationDatetime: "2025-05-16T19:30:54Z",
    optionalDatetime: undefined,
    phoneNumber: "687-123-6990",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["ACUPRESSURE"],
  },
  {
    id: 24,
    name: "Cullen Campany",
    age: 8,
    domicile: "Indonesia",
    complaint: "Optimized methodical local area network",
    therapyExperience: "Bekam",
    email: "bspurdenn@cnbc.com",
    gender: "Male",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Organic even-keeled definition",
    reservationDatetime: "2025-05-14T21:57:15Z",
    optionalDatetime: undefined,
    phoneNumber: "741-141-3578",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["HEALTH_CONSULTATION"],
  },
  {
    id: 25,
    name: "Arthur Matusson",
    age: 65,
    domicile: "Indonesia",
    complaint: "Reactive directional portal",
    therapyExperience: "Accupressure",
    email: "wgiraudeauo@skyrock.com",
    gender: "Male",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: "Open-source bandwidth-monitored model",
    referredBy: "Implemented 3rd generation utilisation",
    reservationDatetime: "2025-05-19T09:00:41Z",
    optionalDatetime: undefined,
    phoneNumber: "726-744-8058",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "LEARNING_TRAINING",
      "NASAL_GURAH_THERAPY",
      "FASDHU_THERAPY",
      "CHIROPRACTIC",
    ],
  },
  {
    id: 26,
    name: "Jule Ashby",
    age: 70,
    domicile: "Indonesia",
    complaint: "Mandatory systemic initiative",
    therapyExperience: "Accupunture",
    email: "jmcaulayp@yelp.com",
    gender: "Male",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Profound leading edge success",
    reservationDatetime: "2025-05-19T19:58:15Z",
    optionalDatetime: undefined,
    phoneNumber: "194-747-7639",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "LEARNING_TRAINING",
      "FASDHU_THERAPY",
      "THROAT_GURAH",
    ],
  },
  {
    id: 27,
    name: "Lanette Clere",
    age: 54,
    domicile: "Indonesia",
    complaint: "Synergistic 6th generation solution",
    therapyExperience: "Accupressure",
    email: "mbroggioq@hc360.com",
    gender: "Female",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Integrated radical architecture",
    reservationDatetime: "2025-05-11T23:11:08Z",
    optionalDatetime: undefined,
    phoneNumber: "786-730-3268",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "HEALTH_CONSULTATION",
      "CHIROPRACTIC",
      "FASDHU_THERAPY",
      "EYE_GURAH_THERAPY",
      "NASAL_GURAH_THERAPY",
    ],
  },
  {
    id: 28,
    name: "Bevan Haimes",
    age: 66,
    domicile: "Indonesia",
    complaint: "Devolved mobile Graphical User Interface",
    therapyExperience: "Sudah pernah",
    email: "pkuhler@msu.edu",
    gender: "Male",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Synergistic impactful utilisation",
    reservationDatetime: "2025-05-09T17:20:01Z",
    optionalDatetime: undefined,
    phoneNumber: "185-918-2069",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "HIJAMAH_BEKAM_THERAPY",
      "LEARNING_TRAINING",
      "CHIROPRACTIC",
    ],
  },
  {
    id: 29,
    name: "Elvyn Ivanitsa",
    age: 32,
    domicile: "Indonesia",
    complaint: "Secured leading edge challenge",
    therapyExperience: "Sudah pernah",
    email: "mmcorkills@marketwatch.com",
    gender: "Male",
    registrationCategory: "REGULAR_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Devolved 4th generation methodology",
    reservationDatetime: "2025-05-19T19:10:19Z",
    optionalDatetime: undefined,
    phoneNumber: "768-339-1623",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: ["CHIROPRACTIC"],
  },
  {
    id: 30,
    name: "Braden Madgwich",
    age: 9,
    domicile: "Indonesia",
    complaint: "Future-proofed local neural-net",
    therapyExperience: "Accupressure",
    email: "ejeffreyst@jugem.jp",
    gender: "Male",
    registrationCategory: "NEW_REGISTRATION",
    accompanyingParticipantName: undefined,
    accompanyingParticipantComplaint: undefined,
    referredBy: "Configurable discrete utilisation",
    reservationDatetime: "2025-05-08T07:20:46Z",
    optionalDatetime: undefined,
    phoneNumber: "104-468-4636",
    createdAt: "2025-05-07T00:00:00Z",
    updatedAt: "2025-05-07T00:00:00Z",
    reservationServices: [
      "HEALTH_CONSULTATION",
      "LEARNING_TRAINING",
      "ACUPRESSURE",
      "EYE_GURAH_THERAPY",
    ],
  },
];
